baseURL = 'https://alexmarquardt.com/'
languageCode = 'en-us'
title = 'Alexander Marquardt'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  logo = "/alexmarquardt.png"

  # Header label configuration
  [params.label]
    text = "Alexander Marquardt"
    icon = "/alexmarquardt.png"
    iconHeight = 30

  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  # Good defaults for a technical site
  ShowToc = true
  TocOpen = false

  mainSections = []

  customCSS = ["css/extended/table.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  elastic = "/elastic/:slug/"
  airbyte = "/airbyte/:slug/"
  mongodb = "/mongodb/:slug/"
  personal = "/personal/:slug/"

