baseURL = "https://alexmarquardt.com/"
canonifyURLs = true
languageCode = 'en-us'
title = 'Alexander Marquardt'
author = 'Alexander Marquardt'
description = "Technical writing on search relevance, data pipelines, and distributed systems at enterprise scale."
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  logo = "alexmarquardt-light.png"  
  images = ["social-card-square.png"]
  logoDark = "alexmarquardt-dark.png"
  favicon = "/favicon.ico"

  # REQUIRED for social cards
  env = "production"
  
  [params.footerAuthor]
    name = "Alexander Marquardt"
    link = "/about/"

  [params.label]
    text = ""
    icon = "alexmarquardt-light.png"
    iconHeight = 96

  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  # Good defaults for a technical site
  ShowToc = true
  TocOpen = false

  mainSections = []

  customCSS = [
    "css/extended/header-center.css",
    "css/extended/extra.css",
    "css/extended/table.css",
    "css/extended/links.css"
  ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[permalinks]
  elastic = "/elastic/:slug/"
  airbyte = "/airbyte/:slug/"
  mongodb = "/mongodb/:slug/"
  personal = "/personal/:slug/"

[taxonomies]
  tags = ""
  categories = ""

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "professional"
    name = "Professional"
    url = "/professional/"
    weight = 3

  [[menu.main]]
    identifier = "personal"
    name = "Personal"
    url = "/personal/"
    weight = 4