baseURL = "https://alexander-marquardt.github.io/alexmarquardt.com/"
canonifyURLs = true
languageCode = 'en-us'
title = 'Alexander Marquardt'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  logo = "/alexmarquardt-light.png"
  logoDark = "/alexmarquardt-dark.png"

  # Header label configuration
  [params.label]
    text = ""
    icon = "/alexmarquardt-light.png"
    iconHeight = 96

  defaultTheme = "light"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  # Good defaults for a technical site
  ShowToc = true
  TocOpen = false

  mainSections = []

  customCSS = ["css/extended/table.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  elastic = "/elastic/:slug/"
  airbyte = "/airbyte/:slug/"
  mongodb = "/mongodb/:slug/"
  personal = "/personal/:slug/"

